name: ðŸš€ Deploy website on push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: ðŸ“¦ Install dependencies
      run: npm install 
    - name: Install TypeScript
      run: npm i -g typescript
    - name: ðŸ— Build
      run: tsc
    - name: Move package.json
      run: mv package.json ./dist/package.json
    - name: Add config
      run: |
        echo 'TOKEN="${{secrets.TOKEN}}"' >> ./dist/.env
        echo 'UNSPLASH_ACCESS_KEY="${{secrets.UNSPLASH_ACCESS_KEY}}' >> ./dist/.env
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: v-buf-17.sparkedhost.us
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        local-dir: ./dist